### ISSUE TITLE
README.md の整理

### ISSUE THREAD

**Issue by sosuke-k** [sosuke-k/hyena#11]
- **Dependencies** の追加
- `go get` = `git clone` + `go install` らしいので、 `go install` いらない
## Dependencies
- `go`

**Comment by sosuke-k** [comment]
`go get -u github.com/sosuke-k/hyena`

じゃないと？

**Comment by sosuke-k** [comment]
インストールした後最初にすることを追記

```
hyena init
hyena add your_first_project
```

**Comment by rooa** [comment]
#27

**Comment by sosuke-k** [comment]
`Support Application` じゃなくて `Supported Applications` または `Application Support`

**Comment by sosuke-k** [comment]
`hyena の一言説明文` 欲しい

**Comment by rooa** [comment]
hyena の説明文は、GIFの上に置くイメージ。

## Hyena

The missing command line tool that ... 云々かんぬん

**Comment by sosuke-k** [comment]
ここまじ決めよう汗

**Comment by sosuke-k** [comment]
`missing` ?

**Comment by sosuke-k** [comment]
欲していたってこと？

**Comment by rooa** [comment]
## Hyena

A command line tool to save & restore your active Apps

_Exclusively for Mac OSX 10.10 or later._
↑これ必要。10.9以前だとJXA使えないから汗

**Comment by rooa** [comment]
あと `Supported Applications` をもっと上に持ってきたほうがいいかなと思ったわ
@sosuke-k どう思う

**Comment by sosuke-k** [comment]
たしかに

**Comment by sosuke-k** [comment]
@rooa 
`Supported Applications` と `Application Support` どっちのほうが自然？

**Comment by rooa** [comment]
`Supported~` のほうが自然に聞こえる
