### ISSUE TITLE
Kobitoの状態復元

### ISSUE THREAD

**Issue by rooa** [sosuke-k/hyena#17]
# Why
- Kobito の復元機能ほしい
# 前提
- JXA/AppleScriptにKobitoのAPIがない
- `kobito-cli` には本家kobitoを開く機能がない
# 解決法
- Kobito.app 立ち上げた後にSystemEventsでキー操作して開く汗
- どのノート開くかは、 `kobito ls` からのタイトル抽出でidentifyする汗

**Comment by sosuke-k** [comment]
## 問題１

```
osascript -l JavaScript kobito/kobito_restore_app.applescript "/Users/katososuke/.config/hyena/kobito_test/kobito.json"
```

だとうまくいくけど

```
hyena restore kobito_test
```

だとちゃんと `key down` してくれない。
