### ISSUE TITLE
Restore の時の try catch をどうするか。

### ISSUE THREAD

**Issue by sosuke-k** [sosuke-k/hyena#30]
①、アプリケーションが入ってない時。
②、`save` した `json` ファイルがない時。

最初は①は `go` にはできないから `jxa` に書いたが
②が①を内包してるかな？と思って
②だけだったら `go` でできるから `util` パッケージに書こうかな？とか思ってる。

**Comment by rooa** [comment]
jxaに書いたほうがいいね。
①のケースはそのままsaveにも使えば良い。
