### ISSUE TITLE
fileWriter でのjson保存をpretty に。

### ISSUE THREAD

**Issue by sosuke-k** [sosuke-k/hyena#32]

**Comment by sosuke-k** [comment]
[How can I pretty-print JSON using JavaScript?](http://stackoverflow.com/questions/4810841/how-can-i-pretty-print-json-using-javascript)

```
JSON.stringify(obj, null, 2)
```

でいけるみたいだけど？

要テスト。

**Comment by rooa** [comment]
明日やります汗

**Comment by sosuke-k** [comment]
インデントと改行つきの文字にする時はよさそうだけど
パースする時大丈夫かな？

**Comment by sosuke-k** [comment]
まあまあ

**Comment by rooa** [comment]
JSON.parseできました
