### ISSUE TITLE
Kobito が起動しているけど１つもウィンドウがない時に save する時のバグ

### ISSUE THREAD

**Issue by sosuke-k** [sosuke-k/hyena#70]
`null（棒）` の前に `ウィンドウを整理（隠れ）` と `すべてを手前に表示` があるので
２つ保存されてしまう。

[![Gyazo](http://i.gyazo.com/2ebc5ea5471350e47514ec59d589a529.png)](http://gyazo.com/2ebc5ea5471350e47514ec59d589a529)

**Comment by rooa** [comment]
ああ、そのケースを考えるのを忘れてた

**Comment by rooa** [comment]
こういう場合は、saveすらしないほうがいいのか？
だよね。

**Comment by sosuke-k** [comment]
そうだね

**Comment by sosuke-k** [comment]
一回ループ回して `null` の数とって、場合分け？
なんかいい方法ある？

**Comment by rooa** [comment]
最初の`null`(仕切っているライン)になるまで下から見ていって、選択可能なものがある/ない判定して、フラグが立たなかったら保存しない、っていう方向でどう？

`windowItems[i].enabled()` みたいにすればboolが :frog:

**Comment by sosuke-k** [comment]
おお、 `enabled()` でいけるのか。
なるほど。

**Comment by rooa** [comment]
ちなみに自分の環境だと
![](http://i.gyazo.com/3d25fd38345f5efe59cdfdafcdaa4b4a.png)

**Comment by rooa** [comment]
なにか開いていれば、下のラインより更に下にクリック可能なウインドウ名が出る。
というわけでenabled判定します

**Comment by sosuke-k** [comment]
ああなるほど、棒の数違うのか。
うぃす！
